<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Playground\Web\DataSource\SQLite3\Player;

use Atlas\Table\Table;

/**
 * @method PlayerRow|null fetchRow($primaryVal)
 * @method PlayerRow[] fetchRows(array $primaryVals)
 * @method PlayerTableSelect select(array $whereEquals = [])
 * @method PlayerRow newRow(array $cols = [])
 * @method PlayerRow newSelectedRow(array $cols)
 */
class PlayerTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'players';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'name' => [
            'name' => 'name',
            'type' => 'TEXT',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'email' => [
            'name' => 'email',
            'type' => 'TEXT',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'created_at' => [
            'name' => 'created_at',
            'type' => 'TEXT',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'id',
        'name',
        'email',
        'created_at',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'name' => null,
        'email' => null,
        'created_at' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
