<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Playground\Web\DataSource\SQLite3\Player;

/**
 * @property mixed $id INTEGER NOT NULL
 * @property mixed $name TEXT NOT NULL
 * @property mixed $email TEXT NOT NULL
 * @property mixed $created_at TEXT NOT NULL
 */
trait PlayerFields
{
}
