<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Playground\Web\DataSource\MySQL\Player;

use Atlas\Table\Row;

/**
 * @property mixed $id mediumint(7,0) unsigned NOT NULL
 * @property mixed $name varchar(191) NOT NULL
 * @property mixed $email varchar(255) NOT NULL
 * @property mixed $created_at datetime NOT NULL
 */
class PlayerRow extends Row
{
    protected $cols = [
        'id' => null,
        'name' => null,
        'email' => null,
        'created_at' => null,
    ];
}
