<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Playground\Web\DataSource\MySQL\SavedCode;

use Atlas\Table\Row;

/**
 * @property mixed $id mediumint(7,0) unsigned NOT NULL
 * @property mixed $player_id mediumint(7,0) unsigned
 * @property mixed $code mediumtext(16777215)
 * @property mixed $hole varchar(255)
 * @property mixed $hash varbinary(32)
 * @property mixed $published tinyint(3,0)
 * @property mixed $ipaddr varbinary(16)
 */
class SavedCodeRow extends Row
{
    protected $cols = [
        'id' => null,
        'player_id' => null,
        'code' => null,
        'hole' => null,
        'hash' => null,
        'published' => null,
        'ipaddr' => null,
    ];
}
