<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Playground\Web\DataSource\MySQL\Error;

/**
 * @property mixed $id mediumint(7,0) unsigned NOT NULL
 * @property mixed $time datetime NOT NULL
 * @property mixed $title varchar(191) NOT NULL
 * @property mixed $trace json
 */
trait ErrorFields
{
}
