<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Playground\Web\DataSource\MySQL\Error;

use Atlas\Table\Row;

/**
 * @property mixed $id mediumint(7,0) unsigned NOT NULL
 * @property mixed $time datetime NOT NULL
 * @property mixed $title varchar(191) NOT NULL
 * @property mixed $trace json
 */
class ErrorRow extends Row
{
    protected $cols = [
        'id' => null,
        'time' => null,
        'title' => null,
        'trace' => null,
    ];
}
