<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Playground\Web\DataSource\MySQL\Error;

use Atlas\Table\Table;

/**
 * @method ErrorRow|null fetchRow($primaryVal)
 * @method ErrorRow[] fetchRows(array $primaryVals)
 * @method ErrorTableSelect select(array $whereEquals = [])
 * @method ErrorRow newRow(array $cols = [])
 * @method ErrorRow newSelectedRow(array $cols)
 */
class ErrorTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'errors';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'mediumint unsigned',
            'size' => 7,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'time' => [
            'name' => 'time',
            'type' => 'datetime',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'title' => [
            'name' => 'title',
            'type' => 'varchar',
            'size' => 191,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'trace' => [
            'name' => 'trace',
            'type' => 'json',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'id',
        'time',
        'title',
        'trace',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'time' => null,
        'title' => null,
        'trace' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
