<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Playground\Web\DataSource\SQLite3\SavedCode;

use Atlas\Table\Row;

/**
 * @property mixed $id INTEGER NOT NULL
 * @property mixed $player_id INTEGER NOT NULL
 * @property mixed $code TEXT NOT NULL
 * @property mixed $hole TEXT NOT NULL
 * @property mixed $hash BLOB NOT NULL
 */
class SavedCodeRow extends Row
{
    protected $cols = [
        'id' => null,
        'player_id' => null,
        'code' => null,
        'hole' => null,
        'hash' => null,
    ];
}
