<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Playground\Web\DataSource\SQLite3\SavedCode;

use Atlas\Table\Table;

/**
 * @method SavedCodeRow|null fetchRow($primaryVal)
 * @method SavedCodeRow[] fetchRows(array $primaryVals)
 * @method SavedCodeTableSelect select(array $whereEquals = [])
 * @method SavedCodeRow newRow(array $cols = [])
 * @method SavedCodeRow newSelectedRow(array $cols)
 */
class SavedCodeTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'saved_codes';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'player_id' => [
            'name' => 'player_id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'code' => [
            'name' => 'code',
            'type' => 'TEXT',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'hole' => [
            'name' => 'hole',
            'type' => 'TEXT',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'hash' => [
            'name' => 'hash',
            'type' => 'BLOB',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'id',
        'player_id',
        'code',
        'hole',
        'hash',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'player_id' => null,
        'code' => null,
        'hole' => null,
        'hash' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
