<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Playground\Web\DataSource\SQLite3\SavedCode;

/**
 * @property mixed $id INTEGER NOT NULL
 * @property mixed $player_id INTEGER NOT NULL
 * @property mixed $code TEXT NOT NULL
 * @property mixed $hole TEXT NOT NULL
 * @property mixed $hash BLOB NOT NULL
 */
trait SavedCodeFields
{
}
