<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Playground\Web\DataSource\SQLite3\Password;

use Atlas\Table\Row;

/**
 * @property mixed $id INTEGER NOT NULL
 * @property mixed $player_id INTEGER NOT NULL
 * @property mixed $hash TEXT NOT NULL
 * @property mixed $created_at TEXT NOT NULL
 */
class PasswordRow extends Row
{
    protected $cols = [
        'id' => null,
        'player_id' => null,
        'hash' => null,
        'created_at' => null,
    ];
}
