<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Playground\Web\DataSource\SQLite3\Password;

use Atlas\Table\Table;

/**
 * @method PasswordRow|null fetchRow($primaryVal)
 * @method PasswordRow[] fetchRows(array $primaryVals)
 * @method PasswordTableSelect select(array $whereEquals = [])
 * @method PasswordRow newRow(array $cols = [])
 * @method PasswordRow newSelectedRow(array $cols)
 */
class PasswordTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'passwords';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'player_id' => [
            'name' => 'player_id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'hash' => [
            'name' => 'hash',
            'type' => 'TEXT',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'created_at' => [
            'name' => 'created_at',
            'type' => 'TEXT',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'id',
        'player_id',
        'hash',
        'created_at',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'player_id' => null,
        'hash' => null,
        'created_at' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
