<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Playground\Web\DataSource\SQLite3\Password;

/**
 * @property mixed $id INTEGER NOT NULL
 * @property mixed $player_id INTEGER NOT NULL
 * @property mixed $hash TEXT NOT NULL
 * @property mixed $created_at TEXT NOT NULL
 */
trait PasswordFields
{
}
