<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Playground\Web\DataSource\SQLite3\Error;

/**
 * @property mixed $id INTEGER NOT NULL
 * @property mixed $time TEXT NOT NULL
 * @property mixed $title TEXT NOT NULL
 * @property mixed $trace TEXT
 */
trait ErrorFields
{
}
