<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Playground\Web\DataSource\SQLite3\Error;

use Atlas\Table\Row;

/**
 * @property mixed $id INTEGER NOT NULL
 * @property mixed $time TEXT NOT NULL
 * @property mixed $title TEXT NOT NULL
 * @property mixed $trace TEXT
 */
class ErrorRow extends Row
{
    protected $cols = [
        'id' => null,
        'time' => null,
        'title' => null,
        'trace' => null,
    ];
}
