<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Playground\Web\DataSource\MySQL\Password;

use Atlas\Table\Table;

/**
 * @method PasswordRow|null fetchRow($primaryVal)
 * @method PasswordRow[] fetchRows(array $primaryVals)
 * @method PasswordTableSelect select(array $whereEquals = [])
 * @method PasswordRow newRow(array $cols = [])
 * @method PasswordRow newSelectedRow(array $cols)
 */
class PasswordTable extends Table
{
    const DRIVER = 'mysql';

    const NAME = 'passwords';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'mediumint unsigned',
            'size' => 7,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'player_id' => [
            'name' => 'player_id',
            'type' => 'mediumint unsigned',
            'size' => 7,
            'scale' => 0,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'hash' => [
            'name' => 'hash',
            'type' => 'varchar',
            'size' => 255,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'id',
        'player_id',
        'hash',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'player_id' => null,
        'hash' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
