<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Playground\Web\DataSource\MySQL\Password;

/**
 * @property mixed $id mediumint(7,0) unsigned NOT NULL
 * @property mixed $player_id mediumint(7,0) unsigned NOT NULL
 * @property mixed $hash varchar(255)
 */
trait PasswordFields
{
}
